src/read.cob, src/server.cob
After this commit, each incoming packet is read in its entirety into a large buffer, and then decoded only after everything has been read. This has the following benefits over decoding while reading:
* Separation of concerns (e.g. VarInt decoder is not dependent on the socket implementation).
* Reduces code duplication for consuming data & handling errors.
* Allows reading packets of any valid length vs. just 64k.
* Would allow for unit-testing the decoder implementations without having to create a socket.
* Will allow for asynchronous receipt of packet data while the game loop continues running. The packet is only parsed once fully received.
=> feat: Uncouple packet reading from packet decoding

Dockerfile, Makefile, cpp/cobolcraft_util.cpp, cpp/cobolcraft_util.h, src/server.cob, src/socket.cob, src/util.cob
Before this patch, receiving packets from the client was a blocking operation, and it was impossible to do basically anything else at all. Now, each socket read only gets a very short timeout, so no matter how much data could be read, the call will complete - and we will be able to perform other stuff before trying to read again.
Also in this patch, a custom C++ util module is added that has one function implemented to retrieve the system time in milliseconds. Using this, the game update + socket read loop can be timed precisely enough to achieve Minecraft's 20 ticks per second. The idea is to first perform any game logic, then spend the rest of the tick doing socket communication.
Since the read is now (somewhat) async, it should be possible to extend this for multiplayer as well …
=> feat: Begin implementation of a timed game loop

CBL_GC_SOCKET/cob_socket.cpp, README.md
This patch fixes a bug in the CBL_GC_SOCKET library. The snprintf call requires the second parameter to be the size of the buffer including the null terminator. The buffer size is 6, not 5.
=> fix: Fix improper `snprintf` call in CBL_GC_SOCKET

README.md, src/packets/chunkdata.cob, src/server.cob
When the server is starting, it now generates initial world data that is stored in RAM. When a player logs in, the chunks are encoded dynamically and sent to the player. This is half of what is needed for block placement/destruction to be effective - the other half is actually handling the place/destroy packets sent by the client and updating the data in RAM.
For now, a fixed 7x7 chunks are generated, since the performance is not yet optimized for more, and the network usage is quite high.
=> feat: Store chunk data in RAM

README.md, src/server.cob
This patch adds a very limited first implementation for placing blocks. Due to having no registry data available yet, the item-to-block mapping has to be hardcoded. This means that for now, only two block types can actually be placed.
=> feat: Add initial implementation for placing blocks

Dockerfile, Makefile
This patch avoids downloading the Minecraft server .jar and extracting the JSON data from it each time the image is built, even when only the source files changed. This should speed up builds in CI and reduce load on the provider hosting the .jar file.
=> chore: Enable Docker to cache the data extraction layer

src/blocks.cob, src/copybooks/DD-BLOCKS.cpy, src/json-parse.cob, src/server.cob, tests/json-parse.test.cob
Continuation of #58. Similar to that PR, the protocol IDs of block states are now loaded from the blocks.json data file at runtime. This improves robustness for future changes. It also prepares us to correlate item IDs to block IDs in a future patch, to enable placing arbitrary blocks.
To achieve this goal, the JSON parser is extended to support parsing arrays. The blocks.json file is parsed once at startup and its contents stored in a shared data structure such that the default block state ID of any named block can be easily retrieved.
=> feat: Load block state IDs from blocks.json

src/server.cob
For the vast majority of cases, this behavior is more accurate. Exceptions include blocks that should be replaced directly instead of placing the block adjacent to them, which needs to be handled separately.
=> fix: Check for air before placing blocks

src/packets/ack-block-change.cob, src/packets/add-player.cob, src/packets/block-update.cob, src/packets/chunkdata.cob, src/packets/entity-animation.cob, src/packets/feature-flags.cob, src/packets/keepalive.cob, src/packets/login-disconnect.cob, src/packets/login-play.cob, src/packets/login-success.cob, src/packets/player-chat.cob, src/packets/remove-entity.cob, src/packets/remove-player.cob, src/packets/set-center-chunk.cob, src/packets/set-container-content.cob, src/packets/set-equipment.cob, src/packets/set-head-rotation.cob, src/packets/set-player-position.cob, src/packets/spawn-entity.cob, src/packets/status.cob, src/packets/system-chat.cob, src/packets/teleport-entity.cob, src/packets/update-time.cob, src/server.cob
The packet listings on wiki.vg use hexadecimal notation for the packet IDs. Doing the same in the code makes it easier to reference the wiki, especially for future upgrades where packet IDs may change.
=> refactor: Use hexadecimal literals for packet IDs

README.md, cpp/cobolcraft_util.cpp, src/server.cob, src/util.cob
This patch is an initial implementation of server commands. "help" and "stop" are supported. Since GnuCOBOL's `ACCEPT` is always blocking when reading from the console, a non-blocking console read was implemented in C++.
=> feat: Implement a server console

src/json-parse.cob, tests/json-parse.test.cob
This is needed in preparation for Minecraft 1.20.5, where blocks.json now contains floating-point numbers that must be understood by our parser.
=> feat: Implement JSON float parser

src/encode.cob, src/packets.cob, tests/encode.test.cob
This patch adds a helper to compute the length of an integer encoded as VarInt without having to do the encoding, to improve performance.
=> fix: Optimize VarInt length computation

src/blocks.cob, src/copybooks/DD-BLOCKS.cpy, src/json-parse.cob, src/registries.cob, src/server.cob, tests/json-parse.test.cob
This patch improves the performance of JSON parsing, and parsing of blocks.json in particular. Overall, a reduction from 1050ms down to 460ms is observed.
The benefits come mostly from the removal of redundant operations: Explicit failure checks, for instance, can often be avoided without downsides if the next instruction(s) are able to deal with a failure condition themselves already.
Further improvements are possible by avoiding string parsing in JsonParse-SkipValue, and avoiding repetitive calls to LENGTH.
=> fix: Optimize parsing of blocks.json

README.md, src/blocks.cob, src/copybooks/DD-BLOCKS.cpy, src/items/slab.cob
As described in the previous PR, #107, we now parse the type attribute of blocks in the blocks.json file - this can then be used to iterate over blocks looking for a type of "minecraft:slab", such that the slab placement handler is automatically registered for each slab type.
=> feat: Add support for all slab types

src/items/slab.cob
We now correctly handle an edge-case of slab placement. Imagine a single bottom slab of block type X, and above it a single bottom slab of a different type Y. When the player has a Y slab in their hand and clicks the bottom slab on its top face, one would imagine that no block placement happens, since clicking a top face usually places a bottom slab above the clicked block, but a bottom slab of type Y is already present there, blocking placement. However, this is not what Minecraft does. Instead, the Y slab is placed through the existing Y slab, doubling it. This case is now properly handled. Similar behavior is observed when clicking the sides of blocks with unusual geometry, such as hoppers, which now work as expected, too.
=> fix: Improve slab doubling when placed

README.md, src/items/button.cob, src/server.cob
All button variants can now be placed and are correctly oriented in the world, whether on walls, or on the top or bottom of blocks.
=> feat: Add support for button placement

src/world.cob
The logic was flawed; we should compute the minimum distance of a chunk to any player, and if that is greater than the threshold, unload the chunk.
=> fix: Use minimum distance for chunk unloading

src/world.cob
By using a single INITIALIZE statement instead of looping, the time to allocate a chunk is reduced from multiple milliseconds to microseconds. In my tests, a speedup of 400-500x is observed.
=> fix: Optimize chunk allocation

cpp/cobolcraft_util.cpp, cpp/cobolcraft_util.h, tests/cobolcraft_util.test.cob
This patch is made in preparation for supporting the "Anvil" region format, which requires zlib/deflate compression and decompression.
=> feat: Add zlib compression functions

src/copybooks/DD-WORLD.cpy, src/world.cob
This patch significantly reduces the chunk loading time in a flat world, and likely in any other world type, too. Performance improvements of 55% were measured. The largest reductions come from using an INITIALIZE statement to set an entire chunk to a single block type, and from precomputing `2 ** PALETTE-BITS` and using a single DIVIDE statement with a REMAINDER clause.
Each partial change in this patch was independently checked to ensure there are no regressions anywhere.
=> fix: Optimize chunk loading

.gitignore, Dockerfile, Makefile
By generating output files as individual Make targets and linking only as the final step, it becomes possible to build in parallel: e.g. `make -j $(nproc)` to use the available number of CPU cores. On a 12-core, 24-thread system, this reduces the build time by 75% with much of the remaining time spent linking, which is unavoidable. Additionally, incremental builds are now possible, where not every source file has to be recompiled if just one has changed.
=> chore: Support building in parallel

README.md, src/items/trapdoor.cob, src/server.cob
Trapdoor blocks are now correctly oriented when placed, and both the top and bottom variant are accessible depending on the click position.
=> feat: Implement placing of trapdoor blocks

src/server.cob
PR #183 unfortunately introduced a logic bug where it was impossible to place any block unless sneaking.
=> fix: Fix block placement not possible unless sneaking

src/items/bucket.cob, src/items/lava-bucket.cob, src/items/water-bucket.cob, src/server.cob
This patch adds support for the main bucket types, allowing players to place and remove water and lava source blocks. This is rather straight-forward for the most part, as long as the player is clicking on a non-fluid block to place or remove a fluid next to it. However, the player may also be far enough away such that they are not in reach of any such block, but would be in reach of an existing fluid block. This scenario does NOT trigger a "use item on" packet to be sent. Instead, the client sends a "use item" packet as if the player was clicking in air, while still expecting the server to calculate the liquid block as the click target and act on it. This requires ray-tracing to be implemented on the server, which is not on my agenda, yet. Hence, this patch simply acknowledges the "use …
=> feat: Add support for buckets (water, lava, empty)

src/packets/login-play.cob, src/packets/player-chat.cob
Continuation of #195 to make use of the data that is now available for chat and dimension types.
Note: For some reason, the chat type needs 1 added to it. This was already the case when using the blob, however. It seems to have changed between 1.20.6 and 1.21. Should keep an eye on this packet.
=> fix: Obtain dimension_type and chat_type from registry

.gitignore, README.md, main.cob, src/commands.cob, src/copybooks/DD-WHITELIST.cpy, src/server.cob, src/whitelist.cob
The whitelist can now support up to 100 players. It is stored in a whitelist.json file in the server directory, using the same format as the official server to be drop-in compatible.
Console and in-game commands are also added to reload the whitelist, list whitelisted players, and add/remove players.
=> feat: Add a persistent JSON file-based whitelist

.gitignore, README.md, main.cob, src/copybooks/DD-SERVER-PROPERTIES.cpy, src/server-properties.cob, src/server.cob
This patch moves away from hardcoding the server configuration in main.cob before compilation, and towards the `server.properties` file also used by the official server.
So far, the parser is rather crude, but works for all supported options (server-port, white-list, motd - basically, everything that was supported before).
=> feat: Use server.properties for configuration

src/chat.cob, src/commands.cob, src/commands/gamemode.cob, src/commands/help.cob, src/commands/save.cob, src/commands/say.cob, src/commands/stop.cob, src/commands/time.cob, src/commands/whitelist.cob, src/copybooks/DD-CALLBACK-COMMAND-EXECUTE.cpy, src/copybooks/DD-COMMANDS.cpy, src/server.cob
The server/in-game commands are no longer part of one big source file, but can instead be registered similar to block and item callbacks, using a program pointer for execution. One limitation still exists in that the node structure (for client-side auto completion) must still be hardcoded. This will be addressed in a future patch.
To enable this change, the `HandleCommand-SendToClient` subroutine is moved to chat.cob as `SendChatMessage` and used throughout.
=> refactor: Split commands into files and make registerable

src/copybooks/DD-CLIENTS.cpy, src/server.cob
See #215. Instead of declaring the buffer statically for each client, which means the maximum amount of memory will always be consumed, it is now a pointer and is allocated/freed when a client connects/disconnects. In effect, unused client slots consume very little memory.
To actually access the buffer, it must be moved to a 01-level BASED item. BASED items cannot be at a level other than 01 or 77, hence the pointer indirection.
=> feat: Allocate client receive buffers dynamically

src/server.cob, src/socket.cob
We always pass a value of 1 as the timeout for Socket-Poll and Socket-Read. Some work can be avoided by declaring it as a constant in the callee.
=> fix: Avoid passing constant-value socket timeout

.github/workflows/test.yml
Adds a step to build the application binary, as well as a step to run and immediately stop it, thereby verifying that the build is superficially okay.
=> chore: Add smoke test to Actions workflow

Dockerfile, Makefile, README.md
The primary motivation for dynamic linking of C++ libraries was the 3rd-party CBL_GC_SOCKET library. Since that is gone, we have no need to produce any shared libraries, and can generate a single standalone binary instead.
=> feat: Link C++ library statically, producing a single binary

src/copybooks/PROC-SKIP-WHITESPACE.cpy
Removed redundant use of variable in comparison.
=> fix: Abbreviate condition in PROC-SKIP-WHITESPACE.cpy

src/players.cob
Apparently we've been storing the player inventory wrong all this time, and Minecraft actually uses different slot numbers on disk vs. over the network. This led to crashes when loading a player.dat file created by the official server where the off-hand slot was occupied, since that slot uses (weirdly) a slot number of -106.
=> fix: Convert inventory slots for player.dat

src/players.cob
When loading a player.dat file generated by the official server or client, it will not have "tag" entries for the inventory slots like it did in the past, but recent versions instead use a "components" compound.
At this time, CobolCraft is unequipped to properly deal with this. Yet, we can cheat a bit and default to the empty network representation of item components. This allows the player to join, at least, even if enchantments etc. will be removed from items.
Inventories saved by CobolCraft should be unaffected by this change.
=> fix: Always set components for loaded inventory items

src/copybooks/DD-WORLD.cpy, src/nbt-decode.cob, src/packets/chunkdata.cob, src/world.cob
This implements encoding/decoding of biome data when saving/loading to/from disk, as well as (crude) encoding of biome data in the chunk data packet. Finally, we can have more than just the plains biome.
For all encoding of biome data, Minecraft uses the same "paletted container" structure as for blocks, but the details are different enough that the code is not easily generalized (at least not in COBOL).
As a refactor, the SkipUntilTag and SkipRemainingTags helper programs are moved to nbt-decode.cob such that the chunk loading can be split into different parts that are all able to call the aforementioned helpers, which is not possible for sibling programs.
=> feat: Add support for biome data in chunk sections

cpp/cobolcraft_util.cpp, cpp/cobolcraft_util.h, src/server.cob
Due to the way we perform game ticks, each tick is very slightly too long. The idea with this patch is to improve (1) the measurement precision and (2) the idle sleep duration, thereby reducing the average overshoot.
Tests show a 10x improvement, from 0.5ms down to 0.05ms on average.
Keepalive and autosave timers were updated accordingly.
=> fix: Make game tick timing more precise

src/server-properties.cob, test.cob, tests/server-properties.test.cob
Splits off server.properties file reading/writing from the actual string manipulation, which allows us to add tests for the latter.
=> refactor: Add tests for server.properties serialize/deserialize

Dockerfile
See #262 for background. "oracular" is not LTS ("noble" was), but the performance benefits likely outweigh that aspect (by a lot).
=> feat(docker): Use base image with GnuCOBOL 3.2

src/items/blocks.cob, src/server.cob
There appears to be a new field "world border hit" before the sequence number. This was messing with our block acknowledge logic.
=> fix: Fix "use_item_on" sequence number decoding

src/server.cob
There are certain player actions that we don't fully handle yet, such as dropping items or placing blocks in survival mode. This previously led to desynchronization between the inventory displayed on the client and the actual one on the server. We now send the full inventory again after any potentially problematic action to avoid this (until there is a better way).
=> fix: Sync inventory after player actions

Makefile, src/inventory/window-crafting.cob
Also set GnuCOBOL to error on the "typing" warning that caught this issue, such that future compilations with similar errors fail. The "typing" warning is only available on GnuCOBOL >= 3.2.
=> fix: Fix numeric move to group item

Makefile, src/server.cob
With some Makefile improvements, the codegen no longer rebuilds when any source file changes; it is only affected by things it actually needs.
This also unlocks static linking against the generated programs since the compilation order is now well-defined.
=> chore: Reduce amount of codegen rebuilds

src/encoding/json-parse.cob, tests/encoding/json-parse.test.cob
Ensures that the offset is unchanged in case the key is not found, allowing the caller to try something else without having to backup the offset before the call.
=> fix: Add test for JsonParse-FindValue

codegen/generators/blocks_loot_table.cob, codegen/templates/blocks_loot_table/condition-random-chance.tpl.cob, src/blocks/slab.cob, src/blocks/tall_grass.cob, src/loot-tables.cob
This allows tall grass, ferns etc. to sometimes drop seeds.
As a drive-by, this patch also completes the list of condition types with TODO placeholders, so there is a clear goal to work towards.
=> feat: Implement `random_chance` loot table condition

src/blocks/air.cob, src/blocks/generic.cob, src/blocks/lava.cob, src/blocks/tall_grass.cob, src/blocks/water.cob
We can look up whether a block is replaceable via the `minecraft:replaceable` tag of the `minecraft:block` registry, removing the need for custom implementations per block type.
=> feat: Implement block replaceability using tag

.github/workflows/test.yml, Dockerfile
Ubuntu 25.04 (plucky) has the same GnuCOBOL version 3.2 as Ubuntu 24.10 (oracular), but both are non-LTS versions with support for only 9 months, and 24.10 support ends soon.
=> chore: Update to Ubuntu 25.04
