src/server.cob

When reading from or writing to a client socket errors, we now simply disconnect the client instead of stopping the entire server.

fix: Treat server/client socket errors differently

---

README.md
src/encode.cob
src/packets/chunkdata.cob
src/server.cob

When logging in, we now send a 9x9 area of chunks to the client. The chunks consist of stone up to a certain height, with air above. Lighting will have to be fixed in a follow-up patch - for now, everything is dark. But still, the world now has stuff in it!
Fixed encoding of negative integers as a drive-by.

feat: Send chunk data

---

.github/workflows/test.yml
.gitignore
Makefile
test.cob
tests/decode.test.cob

This patch adds a test runner to the project. The tests are run on every pull request (and push to `main`) via GitHub Actions. Tests are initially added for the `Decode-VarInt` routine.

chore: Add unit tests for Decode-VarInt

---

README.md
src/packets/add-player.cob
src/packets/player-chat.cob
src/server.cob

Players can now use the chat to send messages to each other.

feat: Implement chat

---

src/server.cob

When a player logs in with a UUID that is already linked to a player on the server, this existing player is now kicked and the player logging in is allowed to do so. This is in contrast to before this patch, where a player could not connect if a previous connection was still live, which can cause issues in case of network timeout, for example.

fix: Disconnect existing player when connecting twice

---

src/copybooks/DD-WORLD.cpy
src/server.cob
src/world.cob

This should make it simpler to implement more complex world state logic, and reuse it across the codebase.

refactor: Move world state to its own file

---

src/server.cob

With this change, all fields related to a player are prefixed with "PLAYER-".

refactor: Rename USERNAME to PLAYER-NAME

---

src/decode.cob

Through restructuring the algorithm, getting rid of FUNCTION MOD, and utilizing a grouped field for byte-to-number conversion yields a 65% reduction in execution time. The benchmark was performed for a representative sample of the entire 32-bit integer space.

fix: Optimize Decode-VarInt

---

src/server.cob

Autosaving every 5 minutes is what the official server does, and helps reduce the amount of data lost if the server is ever forcefully terminated.

feat: Save the world automatically every 5 minutes

---

src/server.cob

Console commands are now properly split at (one or more) space characters, mirroring the official client in its command processing and simplifying future work on the commands, since it is easier to interpret the resulting array.

fix: Improve console command splitting

---

src/copybooks/DD-CLIENT-STATES.cpy
src/server.cob

This reduces reliance on magic numbers.

refactor: Store client state constants in a copybook

---

src/copybooks/DD-CLIENTS.cpy
src/server.cob

This will open up the ability to interact with clients from other files than just server.cob.

refactor: Move client state to copybook

---

src/chat.cob
src/commands.cob
src/copybooks/DD-CLIENTS.cpy
src/server.cob

This patch moves a lot of code around with the goal of extracting console command handling from server.cob into a separate file to aid with readability. This necessitates a larger refactor of the server code to also extract chat broadcasting, as well as multiple server-related features, into their own programs.

refactor: Move command handling to separate file

---

README.md
src/items/rotated-pillar.cob
src/server.cob

This patch adds support for properly oriented block placement of approximately 50 different blocks, all belonging to the "rotated pillar" category.

feat: Add rotated pillar support (logs, basalt, etc.)

---

src/server.cob

The ReceivePacket logic was flawed such that longer packets, where the length VarInt consists of two or more bytes, would incorrectly try to decode their length after just a single byte was received. This caused a failure, and the client would be disconnected.
Note that very few server-bound packets can even be long enough to trigger the bug, which is why it was undetected for so long.

fix: Decode packet length only once all bytes are read

---

src/server.cob

Read directly into the client's packet buffer instead.

fix: Avoid MOVE in packet receive

---

src/server.cob

Before this patch, on rare occasions, when a block was placed or broken, it would flicker very briefly. This is now fixed by sending the "acknowledge block change" packet after any "block update" packets, such that the client keeps showing the predicted new block state until just after they have received all new block states from the server.

fix: Acknowledge block change after world update

---

src/world.cob

While we write our chunk NBT data in the order that makes the most sense for efficient parsing, Minecraft itself emits NBT tags in a way that appears almost random (perhaps a HashMap?). If we want to succeed in loading existing chunk data,  we need to deal with this (at the cost of some performance).

fix: Make chunk NBT parsing order-independent

---

src/decode.cob

The first iteration of VarInt decoding can use fewer instructions than the rest. For a benchmark consisting of every length VarInt uniformly distributed across a large buffer, the execution time is reduced by approximately 17%.

fix: Unroll loop in Decode-VarInt

---

src/packets/chunkdata.cob

For the chunk data packet, the most time is spent encoding the block state palette. We can achieve a 20% performance gain by inlining the operations of Encode-UnsignedLong directly into the packet code. While this breaks the "separation of concerns" principle, this packet is quite heavy overall, so this seems worth it.
Note that adding the `STATIC` keyword to the call yields no improvements. The call has to be avoided altogether.

fix: Inline Encode-UnsignedLong in chunk data packet

---

README.md
src/items/stairs.cob
src/server.cob

Stairs can now be placed with the proper orientation. However, they do not yet change their shape to connect to stairs around them.

feat: Add basic implementation for stairs

---

README.md
src/copybooks/DD-CLIENTS.cpy
src/packets/entity-animation.cob
src/packets/set-container-content.cob
src/packets/world-event.cob

wiki.vg has been shut down and is in the process of being merged into minecraft.wiki.

docs: Update references to wiki.vg

---

.dockerignore
.gitattributes
.gitignore

Adds more text file extensions to .gitattributes, and updates .gitignore and .dockerignore to fit better with the current repository content.

chore: Update dotfiles

---

src/server.cob

Another follow-up to #230. Since reading data from a socket is no longer associated with a 1ms delay in the worst case, we can attempt to read the entire packet (length + ID + payload) in one go. This eliminates the need to do more than one SocketPoll. For short packets (1-byte length and no payload), we previously had to do 2 polls, and in the worst case (5-byte length and 2 MiB payload) there could be 37 polls.
Overall, receive performance should be greatly improved, which can also be seen in Valgrind profiles, where total time spent in SocketPoll is halved.

fix: Receive entire packet at once if possible

---

src/commands/whitelist.cob
src/players.cob
src/server.cob

This functionality was previously duplicated

refactor: Factor out player name-to-UUID conversion

---

src/world.cob

Proto-chunks are partially generated chunks. These are very common in worlds created by the official server or client. Before this patch, we did not read the chunk status and just assumed all chunks were fully generated; this leads to holes in imported worlds. Now, any chunk without blocks is discarded and we generate a new one instead.

fix: Detect proto-chunks when loading chunk data

---

Dockerfile

We don't need all of GnuCOBOL in the final layer; libcob is enough. This reduces the image size from 345 MiB to 132 MiB (62% reduction).

fix(docker): Reduce image size by only including libcob

---

.dockerignore
.github/workflows/test.yml
.gitignore
Makefile
README.md

* test: split compile from link + execute
* split download and unpack for server jar
* automatically set cobc-version

chore: Autodetect cobc version and copybook dependencies

---

src/world.cob

Chunks were previously de-allocated in two places, and reused without any deallocation in another place. This is not future-proof for when we have additional dynamically allocated memory in the chunk structure.

refactor: Move chunk free to separate program

---

Makefile

chore: Fix Makefile dependencies on GnuCOBOL 3.3
